### ISSUE TITLE
Restructure Settings

### ISSUE THREAD

**Issue by fiftyandfifty** [donately/wordpress-plugin-donately-formjs#1]
- [ ] Move Donately out of "Settings" section and into it's own menu item
- [ ] Move Campaigns and create "Setttings" page under Donately menu item
- [ ] Group settings under separate and relevant tabs

**Comment by bryanmonzon** [comment]
This is now down. There are a few steps to adding settings. The file you'll want to look at is in `/lib/admin/settgins/register-settings.php`. If you want to add to default, just find the section and add an array. If you want a new tab, make sure you find all the places `$tab` is called and add the necessary lines of code. 

Alternatively, you can use the filters
- `dntly_settings_general`
- `dntly_settings_email`
- `dntly_settings_sync`
- `dntly_settings_misc`

For adding tabs, you can use these filters.
- `dntly_get_settings`
- `dntly_settings_tabs`

_-A side note, I'm having a bit of trouble with setting the classes properly._
