### ISSUE TITLE
Template Loaders

### ISSUE THREAD

**Issue by bryanmonzon** [donately/wordpress-plugin-donately-formjs#3]
We need to build in the option to use default templates (to be created) and the ability select which template to use.

**Comment by bryanmonzon** [comment]
Let's take a look at this example of template loaders: http://pippinsplugins.com/template-file-loaders-plugins/

**Comment by javanvg** [comment]
Personally, I don't like it. 

JAVAN VAN GRONIGEN
Unnecessary Nay Sayer / Jerk

**Comment by bryanmonzon** [comment]
Thanks for the advice @javanvg
