### ISSUE TITLE
Console Log output - Errors when attempting Sync Campaigns

### ISSUE THREAD

**Issue by elzii** [donately/wordpress-plugin-donately-formjs#6]
Notice:  Undefined index: account_title in donately-wordpress/lib/dntly-api.class.php on line 652

Notice:  Undefined index: dntly_campaign_posttype in donately-wordpress/lib/dntly-api.class.php on line 667

Notice:  Undefined index: environment in donately-wordpress/lib/dntly-api.class.php on line 676

Notice:  Undefined index: environment in donately-wordpress/lib/dntly-api.class.php on line 745

Notice:  Undefined index: account_title in donately-wordpress/lib/dntly-api.class.php on line 652

Notice:  Undefined index: dntly_campaign_posttype in donately-wordpress/lib/dntly-api.class.php on line 667

Notice:  Undefined index: environment in donately-wordpress/lib/dntly-api.class.php on line 676

Notice:  Undefined index: environment in donately-wordpress/lib/dntly-api.class.php on line 745

Notice:  Undefined index: account_title in donately-wordpress/lib/dntly-api.class.php on line 652

Notice:  Undefined index: dntly_campaign_posttype in donately-wordpress/lib/dntly-api.class.php on line 667

Notice:  Undefined index: environment in donately-wordpress/lib/dntly-api.class.php on line 676

Notice:  Undefined index: environment in donately-wordpress/lib/dntly-api.class.php on line 745

Notice:  Undefined index: account_title in donately-wordpress/lib/dntly-api.class.php on line 652

Notice:  Undefined index: dntly_campaign_posttype in donately-wordpress/lib/dntly-api.class.php on line 667

Notice:  Undefined index: environment in donately-wordpress/lib/dntly-api.class.php on line 676

Notice:  Undefined index: environment in donately-wordpress/lib/dntly-api.class.php on line 745

Notice:  Undefined index: account_title in donately-wordpress/lib/dntly-api.class.php on line 652

Notice:  Undefined index: dntly_campaign_posttype in donately-wordpress/lib/dntly-api.class.php on line 667

Notice:  Undefined index: environment in donately-wordpress/lib/dntly-api.class.php on line 676

Notice:  Undefined index: environment in donately-wordpress/lib/dntly-api.class.php on line 745

**Comment by bryanmonzon** [comment]
As we talked about today. Let's do the following:
- [x] `remove dntly_campaign_posttype` and in it's place just use the actual post type dntly_campaigns
- [ ] We don't need 1account_title` at the moment. We can figure out a way to update this in the future if needed. Right now the subdomain field and token is all we really need. 
- [ ] The environment variables can be shut off for now as well. I think it's complicating a system that doesn't need to be. If a developer needs local dev we should set a define a global variable `define( DNTLY_LOCAL_ENVIRONMENT, true );` or something like it.

**Comment by elzii** [comment]
Updated error log with new line numbers to reflect changes on build_url() function in api class.

Notice:  Undefined index: environment in dntly-api.class.php on line 692

Notice:  Undefined index: environment in dntly-api.class.php on line 761

Notice:  Undefined index: environment in dntly-api.class.php on line 692

Notice:  Undefined index: environment in dntly-api.class.php on line 761

Notice:  Undefined index: environment in dntly-api.class.php on line 692

Notice:  Undefined index: environment in dntly-api.class.php on line 761

Notice:  Undefined index: environment in dntly-api.class.php on line 692

Notice:  Undefined index: environment in dntly-api.class.php on line 761

Notice:  Undefined index: environment in dntly-api.class.php on line 692

Notice:  Undefined index: environment in dntly-api.class.php on line 761
